import { RailPrediction } from '../types/rail.types';

export const anacostiaPredictions = [
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '2',
    Line: 'No',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: 'ARR',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: '21',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: '39',
  },
];

export const railPredictions = [
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E05',
    LocationName: 'Georgia Ave-Petworth',
    Min: 'BRD',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K04',
    LocationName: 'Ballston-MU',
    Min: 'BRD',
  },
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '1',
    Line: 'No',
    LocationCode: 'B02',
    LocationName: 'Judiciary Square',
    Min: 'ARR',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C08',
    LocationName: 'Pentagon City',
    Min: 'ARR',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D08',
    LocationName: 'Stadium-Armory',
    Min: 'ARR',
  },
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '1',
    Line: 'No',
    LocationCode: 'E06',
    LocationName: 'Fort Totten',
    Min: 'ARR',
  },
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '2',
    Line: 'No',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: 'ARR',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A10',
    LocationName: 'Medical Center',
    Min: '1',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A13',
    LocationName: 'Twinbrook',
    Min: '1',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D07',
    LocationName: 'Potomac Ave',
    Min: '1',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F05',
    LocationName: 'Navy Yard-Ballpark',
    Min: '1',
  },
  {
    Car: '6',
    Destination: 'Franconia',
    DestinationCode: null,
    DestinationName: 'Franconia',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G03',
    LocationName: 'Addison Road-Seat Pleasant',
    Min: '1',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B06',
    LocationName: 'Fort Totten',
    Min: '2',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B10',
    LocationName: 'Wheaton',
    Min: '2',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C07',
    LocationName: 'Pentagon',
    Min: '2',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C10',
    LocationName: 'Ronald Reagan Washington National Airport',
    Min: '2',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D07',
    LocationName: 'Potomac Ave',
    Min: '2',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E04',
    LocationName: 'Columbia Heights',
    Min: '2',
  },
  {
    Car: '6',
    Destination: 'Huntington',
    DestinationCode: null,
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E08',
    LocationName: "Prince George's Plaza",
    Min: '2',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K03',
    LocationName: 'Virginia Square-GMU',
    Min: '2',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A09',
    LocationName: 'Bethesda',
    Min: '3',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A12',
    LocationName: 'White Flint',
    Min: '3',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D06',
    LocationName: 'Eastern Market',
    Min: '3',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D08',
    LocationName: 'Stadium-Armory',
    Min: '3',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F04',
    LocationName: 'Waterfront',
    Min: '3',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G02',
    LocationName: 'Capitol Heights',
    Min: '3',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K02',
    LocationName: 'Clarendon',
    Min: '3',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B05',
    LocationName: 'Brookland-CUA',
    Min: '4',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B09',
    LocationName: 'Forest Glen',
    Min: '4',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C09',
    LocationName: 'Crystal City',
    Min: '4',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D05',
    LocationName: 'Capitol South',
    Min: '4',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D06',
    LocationName: 'Eastern Market',
    Min: '4',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E03',
    LocationName: 'U Street/African-Amer Civil War Memorial/Cardozo',
    Min: '4',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'J02',
    LocationName: 'Van Dorn Street',
    Min: '4',
  },
  {
    Car: null,
    Destination: 'GLENMONT',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A15',
    LocationName: 'Shady Grove',
    Min: '5',
  },
  {
    Car: null,
    Destination: 'GLENMONT',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A15',
    LocationName: 'Shady Grove',
    Min: '5',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D07',
    LocationName: 'Potomac Ave',
    Min: '5',
  },
  {
    Car: '6',
    Destination: 'Huntington',
    DestinationCode: null,
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E07',
    LocationName: 'West Hyattsville',
    Min: '5',
  },
  {
    Car: null,
    Destination: 'BRANCH AVENUE',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E10',
    LocationName: 'Greenbelt',
    Min: '5',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F03',
    LocationName: "L'Enfant Plaza",
    Min: '5',
  },
  {
    Car: null,
    Destination: 'GREENBELT',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F11',
    LocationName: 'Branch Ave',
    Min: '5',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K01',
    LocationName: 'Court House',
    Min: '5',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'K05',
    LocationName: 'East Falls Church',
    Min: '5',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A08',
    LocationName: 'Friendship Heights',
    Min: '6',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A11',
    LocationName: 'Grosvenor-Strathmore',
    Min: '6',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C08',
    LocationName: 'Pentagon City',
    Min: '6',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D04',
    LocationName: 'Federal Center SW',
    Min: '6',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D05',
    LocationName: 'Capitol South',
    Min: '6',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E02',
    LocationName: 'Shaw-Howard U',
    Min: '6',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G01',
    LocationName: 'Benning Road',
    Min: '6',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B04',
    LocationName: 'Rhode Island Ave-Brentwood',
    Min: '7',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B08',
    LocationName: 'Silver Spring',
    Min: '7',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'C05',
    LocationName: 'Rosslyn',
    Min: '7',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D06',
    LocationName: 'Eastern Market',
    Min: '7',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F02',
    LocationName: 'Archives-Navy Memorial-Penn Quarter',
    Min: '7',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'F03',
    LocationName: "L'Enfant Plaza",
    Min: '7',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A07',
    LocationName: 'Tenleytown-AU',
    Min: '8',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A14',
    LocationName: 'Rockville',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C07',
    LocationName: 'Pentagon',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D03',
    LocationName: "L'Enfant Plaza",
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D04',
    LocationName: 'Federal Center SW',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D05',
    LocationName: 'Capitol South',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E01',
    LocationName: 'Mt Vernon Sq 7th St-Convention Center',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E06',
    LocationName: 'Fort Totten',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Branch Ave',
    DestinationCode: null,
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E09',
    LocationName: 'College Park-U of Md',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F10',
    LocationName: 'Suitland',
    Min: '8',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A10',
    LocationName: 'Medical Center',
    Min: '9',
  },
  {
    Car: null,
    Destination: 'SHADY GROVE',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B11',
    LocationName: 'Glenmont',
    Min: '9',
  },
  {
    Car: null,
    Destination: 'SHADY GROVE',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B11',
    LocationName: 'Glenmont',
    Min: '9',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B35',
    LocationName: 'NoMa-Gallaudet',
    Min: '9',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D02',
    LocationName: 'Smithsonian',
    Min: '9',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D03',
    LocationName: "L'Enfant Plaza",
    Min: '9',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'F02',
    LocationName: 'Archives-Navy Memorial-Penn Quarter',
    Min: '9',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'K04',
    LocationName: 'Ballston-MU',
    Min: '9',
  },
  {
    Car: null,
    Destination: 'LARGO CENTER',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'N06',
    LocationName: 'Wiehle-Reston East',
    Min: '9',
  },
  {
    Car: null,
    Destination: 'LARGO CENTER',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '2',
    Line: 'SV',
    LocationCode: 'N06',
    LocationName: 'Wiehle-Reston East',
    Min: '9',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A06',
    LocationName: 'Van Ness-UDC',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B07',
    LocationName: 'Takoma',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'C04',
    LocationName: 'Foggy Bottom-GWU',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C06',
    LocationName: 'Arlington Cemetery',
    Min: '10',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C13',
    LocationName: 'King St-Old Town',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D04',
    LocationName: 'Federal Center SW',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D08',
    LocationName: 'Stadium-Armory',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E01',
    LocationName: 'Mt Vernon Sq 7th St-Convention Center',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E05',
    LocationName: 'Georgia Ave-Petworth',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'F01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'G04',
    LocationName: 'Morgan Boulevard',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'K03',
    LocationName: 'Virginia Square-GMU',
    Min: '10',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A09',
    LocationName: 'Bethesda',
    Min: '11',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A13',
    LocationName: 'Twinbrook',
    Min: '11',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B03',
    LocationName: 'Union Station',
    Min: '11',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'D01',
    LocationName: 'Federal Triangle',
    Min: '11',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D02',
    LocationName: 'Smithsonian',
    Min: '11',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D03',
    LocationName: "L'Enfant Plaza",
    Min: '11',
  },
  {
    Car: '6',
    Destination: 'Branch Ave',
    DestinationCode: null,
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E08',
    LocationName: "Prince George's Plaza",
    Min: '11',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F09',
    LocationName: 'Naylor Road',
    Min: '11',
  },
  {
    Car: null,
    Destination: 'NEW CARROLLTON',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K08',
    LocationName: 'Vienna/Fairfax-GMU',
    Min: '11',
  },
  {
    Car: null,
    Destination: 'NEW CARROLLTON',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K08',
    LocationName: 'Vienna/Fairfax-GMU',
    Min: '11',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A05',
    LocationName: 'Cleveland Park',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C01',
    LocationName: 'Metro Center',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'C03',
    LocationName: 'Farragut West',
    Min: '12',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C12',
    LocationName: 'Braddock Road',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D01',
    LocationName: 'Federal Triangle',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E01',
    LocationName: 'Mt Vernon Sq 7th St-Convention Center',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E02',
    LocationName: 'Shaw-Howard U',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F02',
    LocationName: 'Archives-Navy Memorial-Penn Quarter',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Wiehle Rest',
    DestinationCode: null,
    DestinationName: 'Wiehle Rest',
    Group: '2',
    Line: 'SV',
    LocationCode: 'G03',
    LocationName: 'Addison Road-Seat Pleasant',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'K02',
    LocationName: 'Clarendon',
    Min: '12',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B02',
    LocationName: 'Judiciary Square',
    Min: '13',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B06',
    LocationName: 'Fort Totten',
    Min: '13',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B10',
    LocationName: 'Wheaton',
    Min: '13',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'C02',
    LocationName: 'McPherson Square',
    Min: '13',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C05',
    LocationName: 'Rosslyn',
    Min: '13',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D02',
    LocationName: 'Smithsonian',
    Min: '13',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E03',
    LocationName: 'U Street/African-Amer Civil War Memorial/Cardozo',
    Min: '13',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E04',
    LocationName: 'Columbia Heights',
    Min: '13',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'K01',
    LocationName: 'Court House',
    Min: '13',
  },
  {
    Car: '-',
    Destination: 'N Carrollton',
    DestinationCode: null,
    DestinationName: 'N Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K07',
    LocationName: 'Dunn Loring-Merrifield',
    Min: '13',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A04',
    LocationName: 'Woodley Park-Zoo/Adams Morgan',
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A08',
    LocationName: 'Friendship Heights',
    Min: '14',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A12',
    LocationName: 'White Flint',
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'C01',
    LocationName: 'Metro Center',
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C02',
    LocationName: 'McPherson Square',
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E02',
    LocationName: 'Shaw-Howard U',
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Branch Ave',
    DestinationCode: null,
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E07',
    LocationName: 'West Hyattsville',
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F03',
    LocationName: "L'Enfant Plaza",
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F08',
    LocationName: 'Southern Avenue',
    Min: '14',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'C01',
    LocationName: 'Metro Center',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'C02',
    LocationName: 'McPherson Square',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C03',
    LocationName: 'Farragut West',
    Min: '15',
  },
  {
    Car: null,
    Destination: 'GREENBELT',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C15',
    LocationName: 'Huntington',
    Min: '15',
  },
  {
    Car: null,
    Destination: 'GREENBELT',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '2',
    Line: 'YL',
    LocationCode: 'C15',
    LocationName: 'Huntington',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'D01',
    LocationName: 'Federal Triangle',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E03',
    LocationName: 'U Street/African-Amer Civil War Memorial/Cardozo',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E03',
    LocationName: 'U Street/African-Amer Civil War Memorial/Cardozo',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E04',
    LocationName: 'Columbia Heights',
    Min: '15',
  },
  {
    Car: null,
    Destination: 'HUNTINGTON',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E10',
    LocationName: 'Greenbelt',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'G02',
    LocationName: 'Capitol Heights',
    Min: '15',
  },
  {
    Car: null,
    Destination: 'FRAN/SPRING',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G05',
    LocationName: 'Largo Town Center',
    Min: '15',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A01',
    LocationName: 'Metro Center',
    Min: '16',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A03',
    LocationName: 'Dupont Circle',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A07',
    LocationName: 'Tenleytown-AU',
    Min: '16',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A11',
    LocationName: 'Grosvenor-Strathmore',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B05',
    LocationName: 'Brookland-CUA',
    Min: '16',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B09',
    LocationName: 'Forest Glen',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'C01',
    LocationName: 'Metro Center',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C04',
    LocationName: 'Foggy Bottom-GWU',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'C05',
    LocationName: 'Rosslyn',
    Min: '16',
  },
  {
    Car: '-',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C14',
    LocationName: 'Eisenhower Avenue',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D01',
    LocationName: 'Federal Triangle',
    Min: '16',
  },
  {
    Car: null,
    Destination: 'VIENNA/FAIRFAX',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D13',
    LocationName: 'New Carrollton',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F07',
    LocationName: 'Congress Heights',
    Min: '16',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C03',
    LocationName: 'Farragut West',
    Min: '17',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'C03',
    LocationName: 'Farragut West',
    Min: '17',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C04',
    LocationName: 'Foggy Bottom-GWU',
    Min: '17',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C10',
    LocationName: 'Ronald Reagan Washington National Airport',
    Min: '17',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E02',
    LocationName: 'Shaw-Howard U',
    Min: '17',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E06',
    LocationName: 'Fort Totten',
    Min: '17',
  },
  {
    Car: '-',
    Destination: 'Huntington',
    DestinationCode: null,
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E09',
    LocationName: 'College Park-U of Md',
    Min: '17',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F04',
    LocationName: 'Waterfront',
    Min: '17',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'G01',
    LocationName: 'Benning Road',
    Min: '17',
  },
  {
    Car: '-',
    Destination: 'N Carrollton',
    DestinationCode: null,
    DestinationName: 'N Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K06',
    LocationName: 'West Falls Church-VT/UVA',
    Min: '17',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'N04',
    LocationName: 'Spring Hill',
    Min: '17',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A02',
    LocationName: 'Farragut North',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A02',
    LocationName: 'Farragut North',
    Min: '18',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A14',
    LocationName: 'Rockville',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B04',
    LocationName: 'Rhode Island Ave-Brentwood',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'C02',
    LocationName: 'McPherson Square',
    Min: '18',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C09',
    LocationName: 'Crystal City',
    Min: '18',
  },
  {
    Car: '-',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C13',
    LocationName: 'King St-Old Town',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D02',
    LocationName: 'Smithsonian',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D12',
    LocationName: 'Landover',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E04',
    LocationName: 'Columbia Heights',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E05',
    LocationName: 'Georgia Ave-Petworth',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F05',
    LocationName: 'Navy Yard-Ballpark',
    Min: '18',
  },
  {
    Car: '-',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G04',
    LocationName: 'Morgan Boulevard',
    Min: '18',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A06',
    LocationName: 'Van Ness-UDC',
    Min: '19',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B08',
    LocationName: 'Silver Spring',
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C02',
    LocationName: 'McPherson Square',
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'C03',
    LocationName: 'Farragut West',
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'C04',
    LocationName: 'Foggy Bottom-GWU',
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'C04',
    LocationName: 'Foggy Bottom-GWU',
    Min: '19',
  },
  {
    Car: '-',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C12',
    LocationName: 'Braddock Road',
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D03',
    LocationName: "L'Enfant Plaza",
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E01',
    LocationName: 'Mt Vernon Sq 7th St-Convention Center',
    Min: '19',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: '19',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'N03',
    LocationName: 'Greensboro',
    Min: '19',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A01',
    LocationName: 'Metro Center',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A03',
    LocationName: 'Dupont Circle',
    Min: '20',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A10',
    LocationName: 'Medical Center',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C01',
    LocationName: 'Metro Center',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'C03',
    LocationName: 'Farragut West',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C05',
    LocationName: 'Rosslyn',
    Min: '20',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C08',
    LocationName: 'Pentagon City',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E05',
    LocationName: 'Georgia Ave-Petworth',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E05',
    LocationName: 'Georgia Ave-Petworth',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E06',
    LocationName: 'Fort Totten',
    Min: '20',
  },
  {
    Car: '-',
    Destination: 'Franconia',
    DestinationCode: null,
    DestinationName: 'Franconia',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G03',
    LocationName: 'Addison Road-Seat Pleasant',
    Min: '20',
  },
  {
    Car: '-',
    Destination: 'N Carrollton',
    DestinationCode: null,
    DestinationName: 'N Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K05',
    LocationName: 'East Falls Church',
    Min: '20',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A05',
    LocationName: 'Cleveland Park',
    Min: '21',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A13',
    LocationName: 'Twinbrook',
    Min: '21',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B07',
    LocationName: 'Takoma',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B35',
    LocationName: 'NoMa-Gallaudet',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'C04',
    LocationName: 'Foggy Bottom-GWU',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'C05',
    LocationName: 'Rosslyn',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D04',
    LocationName: 'Federal Center SW',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D11',
    LocationName: 'Cheverly',
    Min: '21',
  },
  {
    Car: '-',
    Destination: 'Huntington',
    DestinationCode: null,
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E08',
    LocationName: "Prince George's Plaza",
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'F01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F05',
    LocationName: 'Navy Yard-Ballpark',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: '21',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'N02',
    LocationName: 'Tysons Corner',
    Min: '21',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A04',
    LocationName: 'Woodley Park-Zoo/Adams Morgan',
    Min: '22',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A09',
    LocationName: 'Bethesda',
    Min: '22',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '22',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'C02',
    LocationName: 'McPherson Square',
    Min: '22',
  },
  {
    Car: '6',
    Destination: 'Franconia',
    DestinationCode: null,
    DestinationName: 'Franconia',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C06',
    LocationName: 'Arlington Cemetery',
    Min: '22',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C07',
    LocationName: 'Pentagon',
    Min: '22',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D01',
    LocationName: 'Federal Triangle',
    Min: '22',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E04',
    LocationName: 'Columbia Heights',
    Min: '22',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A04',
    LocationName: 'Woodley Park-Zoo/Adams Morgan',
    Min: '23',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B02',
    LocationName: 'Judiciary Square',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B03',
    LocationName: 'Union Station',
    Min: '23',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B10',
    LocationName: 'Wheaton',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'C01',
    LocationName: 'Metro Center',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D02',
    LocationName: 'Smithsonian',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D05',
    LocationName: 'Capitol South',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D10',
    LocationName: 'Deanwood',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E06',
    LocationName: 'Fort Totten',
    Min: '23',
  },
  {
    Car: '-',
    Destination: 'Huntington',
    DestinationCode: null,
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E07',
    LocationName: 'West Hyattsville',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'F02',
    LocationName: 'Archives-Navy Memorial-Penn Quarter',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F04',
    LocationName: 'Waterfront',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F07',
    LocationName: 'Congress Heights',
    Min: '23',
  },
  {
    Car: '-',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G02',
    LocationName: 'Capitol Heights',
    Min: '23',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'J02',
    LocationName: 'Van Dorn Street',
    Min: '23',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'N01',
    LocationName: 'McLean',
    Min: '23',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A05',
    LocationName: 'Cleveland Park',
    Min: '24',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A12',
    LocationName: 'White Flint',
    Min: '24',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B06',
    LocationName: 'Fort Totten',
    Min: '24',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'C05',
    LocationName: 'Rosslyn',
    Min: '24',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C10',
    LocationName: 'Ronald Reagan Washington National Airport',
    Min: '24',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D06',
    LocationName: 'Eastern Market',
    Min: '24',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E03',
    LocationName: 'U Street/African-Amer Civil War Memorial/Cardozo',
    Min: '24',
  },
  {
    Car: '6',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E07',
    LocationName: 'West Hyattsville',
    Min: '24',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K01',
    LocationName: 'Court House',
    Min: '24',
  },
  {
    Car: '-',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K04',
    LocationName: 'Ballston-MU',
    Min: '24',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A03',
    LocationName: 'Dupont Circle',
    Min: '25',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A08',
    LocationName: 'Friendship Heights',
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B02',
    LocationName: 'Judiciary Square',
    Min: '25',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B03',
    LocationName: 'Union Station',
    Min: '25',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C06',
    LocationName: 'Arlington Cemetery',
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C07',
    LocationName: 'Pentagon',
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'D01',
    LocationName: 'Federal Triangle',
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D03',
    LocationName: "L'Enfant Plaza",
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'D09',
    LocationName: 'Minnesota Ave',
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F03',
    LocationName: "L'Enfant Plaza",
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'F03',
    LocationName: "L'Enfant Plaza",
    Min: '25',
  },
  {
    Car: null,
    Destination: 'GREENBELT',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F11',
    LocationName: 'Branch Ave',
    Min: '25',
  },
  {
    Car: '-',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'G01',
    LocationName: 'Benning Road',
    Min: '25',
  },
  {
    Car: '-',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'N01',
    LocationName: 'McLean',
    Min: '25',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A06',
    LocationName: 'Van Ness-UDC',
    Min: '26',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A11',
    LocationName: 'Grosvenor-Strathmore',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '26',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B09',
    LocationName: 'Forest Glen',
    Min: '26',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C09',
    LocationName: 'Crystal City',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'D02',
    LocationName: 'Smithsonian',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D07',
    LocationName: 'Potomac Ave',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E02',
    LocationName: 'Shaw-Howard U',
    Min: '26',
  },
  {
    Car: '-',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'E06',
    LocationName: 'Fort Totten',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E07',
    LocationName: 'West Hyattsville',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E08',
    LocationName: "Prince George's Plaza",
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F08',
    LocationName: 'Southern Avenue',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'K01',
    LocationName: 'Court House',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K02',
    LocationName: 'Clarendon',
    Min: '26',
  },
  {
    Car: '-',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K03',
    LocationName: 'Virginia Square-GMU',
    Min: '26',
  },
  {
    Car: '-',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'N02',
    LocationName: 'Tysons Corner',
    Min: '26',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A02',
    LocationName: 'Farragut North',
    Min: '27',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A07',
    LocationName: 'Tenleytown-AU',
    Min: '27',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B05',
    LocationName: 'Brookland-CUA',
    Min: '27',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C08',
    LocationName: 'Pentagon City',
    Min: '27',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D04',
    LocationName: 'Federal Center SW',
    Min: '27',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F02',
    LocationName: 'Archives-Navy Memorial-Penn Quarter',
    Min: '27',
  },
  {
    Car: '-',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K02',
    LocationName: 'Clarendon',
    Min: '27',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K03',
    LocationName: 'Virginia Square-GMU',
    Min: '27',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A01',
    LocationName: 'Metro Center',
    Min: '28',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A14',
    LocationName: 'Rockville',
    Min: '28',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B35',
    LocationName: 'NoMa-Gallaudet',
    Min: '28',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C13',
    LocationName: 'King St-Old Town',
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'D03',
    LocationName: "L'Enfant Plaza",
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D05',
    LocationName: 'Capitol South',
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D08',
    LocationName: 'Stadium-Armory',
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E01',
    LocationName: 'Mt Vernon Sq 7th St-Convention Center',
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E08',
    LocationName: "Prince George's Plaza",
    Min: '28',
  },
  {
    Car: '-',
    Destination: 'Branch Ave',
    DestinationCode: null,
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'E09',
    LocationName: 'College Park-U of Md',
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'K02',
    LocationName: 'Clarendon',
    Min: '28',
  },
  {
    Car: '-',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'N03',
    LocationName: 'Greensboro',
    Min: '28',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A01',
    LocationName: 'Metro Center',
    Min: '29',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A06',
    LocationName: 'Van Ness-UDC',
    Min: '29',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A07',
    LocationName: 'Tenleytown-AU',
    Min: '29',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B08',
    LocationName: 'Silver Spring',
    Min: '29',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C09',
    LocationName: 'Crystal City',
    Min: '29',
  },
  {
    Car: '6',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E09',
    LocationName: 'College Park-U of Md',
    Min: '29',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F09',
    LocationName: 'Naylor Road',
    Min: '29',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F10',
    LocationName: 'Suitland',
    Min: '29',
  },
  {
    Car: '-',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K01',
    LocationName: 'Court House',
    Min: '29',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'K03',
    LocationName: 'Virginia Square-GMU',
    Min: '29',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K04',
    LocationName: 'Ballston-MU',
    Min: '29',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'K05',
    LocationName: 'East Falls Church',
    Min: '29',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A02',
    LocationName: 'Farragut North',
    Min: '30',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '30',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B04',
    LocationName: 'Rhode Island Ave-Brentwood',
    Min: '30',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B04',
    LocationName: 'Rhode Island Ave-Brentwood',
    Min: '30',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'C07',
    LocationName: 'Pentagon',
    Min: '30',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C10',
    LocationName: 'Ronald Reagan Washington National Airport',
    Min: '30',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'C12',
    LocationName: 'Braddock Road',
    Min: '30',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'D04',
    LocationName: 'Federal Center SW',
    Min: '30',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D06',
    LocationName: 'Eastern Market',
    Min: '30',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E01',
    LocationName: 'Mt Vernon Sq 7th St-Convention Center',
    Min: '30',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '30',
  },
  {
    Car: '-',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'G04',
    LocationName: 'Morgan Boulevard',
    Min: '30',
  },
  {
    Car: '-',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'N04',
    LocationName: 'Spring Hill',
    Min: '30',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A05',
    LocationName: 'Cleveland Park',
    Min: '31',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A08',
    LocationName: 'Friendship Heights',
    Min: '31',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B07',
    LocationName: 'Takoma',
    Min: '31',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'D05',
    LocationName: 'Capitol South',
    Min: '31',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F09',
    LocationName: 'Naylor Road',
    Min: '31',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F10',
    LocationName: 'Suitland',
    Min: '31',
  },
  {
    Car: '6',
    Destination: 'Wiehle',
    DestinationCode: 'N06',
    DestinationName: 'Wiehle-Reston East',
    Group: '2',
    Line: 'SV',
    LocationCode: 'K04',
    LocationName: 'Ballston-MU',
    Min: '31',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A03',
    LocationName: 'Dupont Circle',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B02',
    LocationName: 'Judiciary Square',
    Min: '32',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B05',
    LocationName: 'Brookland-CUA',
    Min: '32',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B35',
    LocationName: 'NoMa-Gallaudet',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'C08',
    LocationName: 'Pentagon City',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D07',
    LocationName: 'Potomac Ave',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D09',
    LocationName: 'Minnesota Ave',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E02',
    LocationName: 'Shaw-Howard U',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'E09',
    LocationName: 'College Park-U of Md',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F02',
    LocationName: 'Archives-Navy Memorial-Penn Quarter',
    Min: '32',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K05',
    LocationName: 'East Falls Church',
    Min: '32',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A04',
    LocationName: 'Woodley Park-Zoo/Adams Morgan',
    Min: '33',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E03',
    LocationName: 'U Street/African-Amer Civil War Memorial/Cardozo',
    Min: '33',
  },
  {
    Car: '-',
    Destination: 'N Carrollton',
    DestinationCode: null,
    DestinationName: 'N Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K07',
    LocationName: 'Dunn Loring-Merrifield',
    Min: '33',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A04',
    LocationName: 'Woodley Park-Zoo/Adams Morgan',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A09',
    LocationName: 'Bethesda',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B03',
    LocationName: 'Union Station',
    Min: '34',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B03',
    LocationName: 'Union Station',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'Franconia',
    DestinationCode: null,
    DestinationName: 'Franconia',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C06',
    LocationName: 'Arlington Cemetery',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'C09',
    LocationName: 'Crystal City',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'D08',
    LocationName: 'Stadium-Armory',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D10',
    LocationName: 'Deanwood',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F03',
    LocationName: "L'Enfant Plaza",
    Min: '34',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F08',
    LocationName: 'Southern Avenue',
    Min: '34',
  },
  {
    Car: '6',
    Destination: 'Wiehle Rest',
    DestinationCode: null,
    DestinationName: 'Wiehle Rest',
    Group: '2',
    Line: 'SV',
    LocationCode: 'K05',
    LocationName: 'East Falls Church',
    Min: '34',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B06',
    LocationName: 'Fort Totten',
    Min: '35',
  },
  {
    Car: '6',
    Destination: 'Franconia',
    DestinationCode: null,
    DestinationName: 'Franconia',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C12',
    LocationName: 'Braddock Road',
    Min: '35',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E04',
    LocationName: 'Columbia Heights',
    Min: '35',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K06',
    LocationName: 'West Falls Church-VT/UVA',
    Min: '35',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A05',
    LocationName: 'Cleveland Park',
    Min: '36',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A10',
    LocationName: 'Medical Center',
    Min: '36',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B02',
    LocationName: 'Judiciary Square',
    Min: '36',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B35',
    LocationName: 'NoMa-Gallaudet',
    Min: '36',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C07',
    LocationName: 'Pentagon',
    Min: '36',
  },
  {
    Car: '6',
    Destination: 'Hntingtn',
    DestinationCode: 'C15',
    DestinationName: 'Huntington',
    Group: '2',
    Line: 'YL',
    LocationCode: 'C10',
    LocationName: 'Ronald Reagan Washington National Airport',
    Min: '36',
  },
  {
    Car: '-',
    Destination: 'Greenbelt',
    DestinationCode: null,
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'YL',
    LocationCode: 'C14',
    LocationName: 'Eisenhower Avenue',
    Min: '36',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F07',
    LocationName: 'Congress Heights',
    Min: '36',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A02',
    LocationName: 'Farragut North',
    Min: '37',
  },
  {
    Car: '6',
    Destination: 'Franconia',
    DestinationCode: null,
    DestinationName: 'Franconia',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C13',
    LocationName: 'King St-Old Town',
    Min: '37',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'D08',
    LocationName: 'Stadium-Armory',
    Min: '37',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D11',
    LocationName: 'Cheverly',
    Min: '37',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F04',
    LocationName: 'Waterfront',
    Min: '37',
  },
  {
    Car: '-',
    Destination: 'N Carrollton',
    DestinationCode: null,
    DestinationName: 'N Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'K06',
    LocationName: 'West Falls Church-VT/UVA',
    Min: '37',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'N04',
    LocationName: 'Spring Hill',
    Min: '37',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A06',
    LocationName: 'Van Ness-UDC',
    Min: '38',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'B01',
    LocationName: 'Gallery Pl-Chinatown',
    Min: '38',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B07',
    LocationName: 'Takoma',
    Min: '38',
  },
  {
    Car: '6',
    Destination: 'Frnconia',
    DestinationCode: 'J03',
    DestinationName: 'Franconia-Springfield',
    Group: '2',
    Line: 'BL',
    LocationCode: 'C08',
    LocationName: 'Pentagon City',
    Min: '38',
  },
  {
    Car: '6',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'E05',
    LocationName: 'Georgia Ave-Petworth',
    Min: '38',
  },
  {
    Car: '6',
    Destination: 'Brnch Av',
    DestinationCode: 'F11',
    DestinationName: 'Branch Ave',
    Group: '2',
    Line: 'GR',
    LocationCode: 'F05',
    LocationName: 'Navy Yard-Ballpark',
    Min: '38',
  },
  {
    Car: '6',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'BL',
    LocationCode: 'G01',
    LocationName: 'Benning Road',
    Min: '38',
  },
  {
    Car: '-',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'A01',
    LocationName: 'Metro Center',
    Min: '39',
  },
  {
    Car: '-',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A01',
    LocationName: 'Metro Center',
    Min: '39',
  },
  {
    Car: '6',
    Destination: 'Glenmont',
    DestinationCode: 'B11',
    DestinationName: 'Glenmont',
    Group: '1',
    Line: 'RD',
    LocationCode: 'B04',
    LocationName: 'Rhode Island Ave-Brentwood',
    Min: '39',
  },
  {
    Car: '6',
    Destination: 'NewCrltn',
    DestinationCode: 'D13',
    DestinationName: 'New Carrollton',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D12',
    LocationName: 'Landover',
    Min: '39',
  },
  {
    Car: '-',
    Destination: 'Grnbelt',
    DestinationCode: 'E10',
    DestinationName: 'Greenbelt',
    Group: '1',
    Line: 'GR',
    LocationCode: 'F06',
    LocationName: 'Anacostia',
    Min: '39',
  },
  {
    Car: '6',
    Destination: 'Vienna',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '2',
    Line: 'OR',
    LocationCode: 'K07',
    LocationName: 'Dunn Loring-Merrifield',
    Min: '39',
  },
  {
    Car: '-',
    Destination: 'Largo',
    DestinationCode: 'G05',
    DestinationName: 'Largo Town Center',
    Group: '1',
    Line: 'SV',
    LocationCode: 'N03',
    LocationName: 'Greensboro',
    Min: '39',
  },
  {
    Car: '6',
    Destination: 'Shady Gr',
    DestinationCode: 'A15',
    DestinationName: 'Shady Grove',
    Group: '2',
    Line: 'RD',
    LocationCode: 'A11',
    LocationName: 'Grosvenor-Strathmore',
    Min: '40',
  },
  {
    Car: null,
    Destination: 'VIENNA/FAIRFAX',
    DestinationCode: 'K08',
    DestinationName: 'Vienna/Fairfax-GMU',
    Group: '1',
    Line: 'OR',
    LocationCode: 'D13',
    LocationName: 'New Carrollton',
    Min: '40',
  },
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '1',
    Line: 'No',
    LocationCode: 'A03',
    LocationName: 'Dupont Circle',
    Min: '---',
  },
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '1',
    Line: 'No',
    LocationCode: 'D06',
    LocationName: 'Eastern Market',
    Min: '---',
  },
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '1',
    Line: 'No',
    LocationCode: 'D07',
    LocationName: 'Potomac Ave',
    Min: '---',
  },
  {
    Car: null,
    Destination: 'ssenger',
    DestinationCode: null,
    DestinationName: 'No Passenger',
    Group: '2',
    Line: 'No',
    LocationCode: 'K07',
    LocationName: 'Dunn Loring-Merrifield',
    Min: '---',
  },
] as RailPrediction[];
